version: '3.4'

services:
  ikev2-vpn:
    image: vlburtsev/ikev2-vpn-server-alpine:3.17
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 500:500/udp
      - 4500:4500/udp
    volumes:
      - type: bind
        source: ikev2-vpn/etc/strongswan.conf
        target: /etc/strongswan.conf
        read_only: true
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 8M

  pptpd-vpn:
    image: vlburtsev/pptp-vpn-server-alpine:3.16
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/ppp:/dev/ppp
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - 1723:1723
    volumes:
      - type: bind
        source: pptpd/chap-secrets
        target: /etc/ppp/chap-secrets
        read_only: true
      - type: bind
        source: pptpd/pptpd-options
        target: /etc/ppp/pptpd-options
        read_only: true
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 8M

  pihole:
    image: pihole/pihole:2023.02.0
    restart: unless-stopped
    shm_size: 256M
    ports:
      - 172.29.0.1:80:80/tcp
      - 172.29.0.1:53:53/tcp
      - 172.29.0.1:53:53/udp
    environment:
      - TZ=Europe/Amsterdam
      - WEBPASSWORD=qazwsxedc123
      - PIHOLE_DNS_=unbound
      - DNSSEC=true
      - INTERFACE=eth0
      - DNSMASQ_LISTENING=single
      - QUERY_LOGGING=false
      - FTLCONF_RATE_LIMIT=600/60
      - FTLCONF_PRIVACYLEVEL=0
      - FTLCONF_DBIMPORT=no
      - FTLCONF_DEBUG_ALL=false
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
      - type: bind
        source: pihole/99-edns.conf
        target: /etc/dnsmasq.d/99-edns.conf
        read_only: true
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 32M

  unbound:
    image: vlburtsev/unbound-alpine:3.16
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 8M

  i2pd:
    image: purplei2p/i2pd:release-2.45.1
    restart: always
    ports:
      - 172.29.0.1:4444:4444
      - 172.29.0.1:4447:4447
      - 172.29.0.1:7656:7656
      - 172.29.0.1:7070:7070
      - 12345:12345
      - 54321:54321/udp
    environment:
      - DEFAULT_ARGS= \
          --datadir=/home/i2pd/data \
          --reseed.verify=true \
          --upnp.enabled=false \
          --http.enabled=true \
          --http.strictheaders=false \
          --http.address=0.0.0.0 \
          --httpproxy.enabled=true \
          --httpproxy.address=0.0.0.0 \
          --socksproxy.enabled=true \
          --socksproxy.address=0.0.0.0 \
          --sam.enabled=true \
          --sam.address=0.0.0.0 \
          --ntcp2.port=12345 \
          --port=54321 \
          --floodfill \
          --bandwidth=X \
          --loglevel=none \
          --limits.openfiles=8192 \
          --limits.transittunnels=10000
    volumes:
      - i2pd:/home/i2pd/data
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 32M

  xd-torrent-client:
    image: vlburtsev/xd-torrent-client-alpine:3.16
    restart: always
    volumes:
      - xd-torrent-client:/home/xd/data
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 32M

  wireguard:
    image: vlburtsev/wireguard-alpine:3.17
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 8M

volumes:
    pihole:
    dnsmasq:
    xd-torrent-client:
    i2pd:

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.29.0.0/24
        gateway: 172.29.0.1
