version: '3.4'

services:
  ikev2-vpn:
    image: vlburtsev/ikev2-vpn-server-alpine:3.16
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 500:500/udp
      - 4500:4500/udp
    volumes:
      - type: bind
        source: /etc/ipsec.secrets
        target: /etc/ipsec.secrets
        read_only: true
      - type: bind
        source: ikev2-vpn/etc/strongswan.conf
        target: /etc/strongswan.conf
        read_only: true
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 8M

  pptpd-vpn:
    image: vlburtsev/pptp-vpn-server-alpine:3.16
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/ppp:/dev/ppp
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - 1723:1723
    volumes:
      - type: bind
        source: pptpd/chap-secrets
        target: /etc/ppp/chap-secrets
        read_only: true
      - type: bind
        source: pptpd/pptpd-options
        target: /etc/ppp/pptpd-options
        read_only: true
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 8M

  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    shm_size: 128M
    ports:
      - 172.29.0.1:80:80/tcp
      - 53:53/tcp
      - 53:53/udp
    environment:
      - TZ=Europe/Amsterdam
      - WEBPASSWORD=qazwsxedc123
      - PIHOLE_DNS_=unbound
      - DNSSEC="true"
      - INTERFACE=eth0
      - DNSMASQ_LISTENING=single
      - QUERY_LOGGING="false"
      - FTLCONF_RATE_LIMIT=600/60
      - FTLCONF_LOGFILE=/dev/null
      - FTLCONF_PRIVACYLEVEL=0
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
      - type: bind
        source: pihole/99-edns.conf
        target: /etc/dnsmasq.d/99-edns.conf
        read_only: true
    deploy:
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 32M

  unbound:
    image: vlburtsev/unbound-alpine:3.16
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 8M

volumes:
    pihole:
    dnsmasq:

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.29.0.0/24
        gateway: 172.29.0.1
